-- Independent pipelines schema (no cross-matching between Pluggy and Oracle AI).
-- Run in Oracle SQL*Plus / SQLcl as a schema owner.

-- 1) Pluggy internet banking extracts
CREATE TABLE transacoes_pluggy (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_user_id VARCHAR2(128) NOT NULL,
  pluggy_item_id VARCHAR2(64),
  pluggy_account_id VARCHAR2(64),
  external_transaction_id VARCHAR2(128) NOT NULL,
  record_type VARCHAR2(24) DEFAULT 'TRANSACTION' NOT NULL,
  transaction_date TIMESTAMP WITH TIME ZONE,
  description VARCHAR2(512),
  amount NUMBER(18,2),
  currency_code VARCHAR2(8),
  account_name VARCHAR2(256),
  account_type VARCHAR2(64),
  balance_amount NUMBER(18,2),
  raw_json CLOB CHECK (raw_json IS JSON),
  source_system VARCHAR2(32) DEFAULT 'PLUGGY' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uq_transacoes_pluggy_ext
  ON transacoes_pluggy (tenant_user_id, external_transaction_id);

CREATE INDEX ix_transacoes_pluggy_dt
  ON transacoes_pluggy (tenant_user_id, transaction_date);

-- 1.1) Pluggy connections catalog (auto-discovery + webhooks)
CREATE TABLE conexoes_bancarias (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_user_id VARCHAR2(128) NOT NULL,
  pluggy_item_id VARCHAR2(128) NOT NULL,
  provider_name VARCHAR2(256),
  status VARCHAR2(64),
  raw_json CLOB CHECK (raw_json IS JSON),
  source_system VARCHAR2(32) DEFAULT 'PLUGGY' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uq_conexoes_bancarias_item
  ON conexoes_bancarias (tenant_user_id, pluggy_item_id);

CREATE INDEX ix_conexoes_bancarias_status
  ON conexoes_bancarias (tenant_user_id, status, updated_at);

-- 2) Oracle AI document pipeline
CREATE TABLE documentos_oracle_ai (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_user_id VARCHAR2(128) NOT NULL,
  source_file_name VARCHAR2(512) NOT NULL,
  source_file_path VARCHAR2(1024),
  source_file_hash VARCHAR2(128) NOT NULL,
  processing_status VARCHAR2(32) DEFAULT 'PENDING' NOT NULL,
  document_type VARCHAR2(64) DEFAULT 'INVOICE',
  extracted_text CLOB,
  extracted_fields_json CLOB CHECK (extracted_fields_json IS JSON),
  raw_result_json CLOB CHECK (raw_result_json IS JSON),
  error_message VARCHAR2(2000),
  source_system VARCHAR2(32) DEFAULT 'ORACLE_AI' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  processed_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uq_documentos_oracle_ai_hash
  ON documentos_oracle_ai (tenant_user_id, source_file_hash);

CREATE INDEX ix_documentos_oracle_ai_status
  ON documentos_oracle_ai (tenant_user_id, processing_status, created_at);
