'use strict';

const { withConnection } = require('../../../workers/lib/oracle-db');

const DEFAULT_TENANT_USER_ID = String(process.env.PLUGGY_TENANT_USER_ID || 'guilherme').trim();
const WEBHOOK_SECRET = String(process.env.PLUGGY_WEBHOOK_SECRET || '').trim();

async function ensureConnectionsTable(conn) {
  const sql = `
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE conexoes_bancarias (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_user_id VARCHAR2(128) NOT NULL,
      pluggy_item_id VARCHAR2(128) NOT NULL,
      provider_name VARCHAR2(256),
      status VARCHAR2(64),
      raw_json CLOB CHECK (raw_json IS JSON),
      source_system VARCHAR2(32) DEFAULT 'PLUGGY' NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;`;
  const uq = `
BEGIN
  EXECUTE IMMEDIATE q'[CREATE UNIQUE INDEX uq_conexoes_bancarias_item ON conexoes_bancarias (tenant_user_id, pluggy_item_id)]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;`;
  await conn.execute(sql);
  await conn.execute(uq);
}

async function upsertConnection(item, tenantUserId) {
  await withConnection(async conn => {
    await ensureConnectionsTable(conn);
    await conn.execute(
      `
MERGE INTO conexoes_bancarias c
USING (SELECT :tenant_user_id AS tenant_user_id, :pluggy_item_id AS pluggy_item_id FROM dual) src
ON (c.tenant_user_id = src.tenant_user_id AND c.pluggy_item_id = src.pluggy_item_id)
WHEN MATCHED THEN UPDATE SET
  c.provider_name = :provider_name,
  c.status = :status,
  c.raw_json = :raw_json,
  c.updated_at = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  tenant_user_id,
  pluggy_item_id,
  provider_name,
  status,
  raw_json,
  source_system,
  created_at,
  updated_at
) VALUES (
  :tenant_user_id,
  :pluggy_item_id,
  :provider_name,
  :status,
  :raw_json,
  'PLUGGY',
  SYSTIMESTAMP,
  SYSTIMESTAMP
)`,
      {
        tenant_user_id: String(tenantUserId || DEFAULT_TENANT_USER_ID),
        pluggy_item_id: String(item?.id || '').trim(),
        provider_name: String(item?.connector?.name || item?.institution?.name || '').slice(0, 256),
        status: String(item?.status || '').slice(0, 64),
        raw_json: JSON.stringify(item || {})
      }
    );
    await conn.commit();
  });
}

async function ensureTransactionsTable(conn) {
  const sql = `
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE transacoes_pluggy (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_user_id VARCHAR2(128) NOT NULL,
      pluggy_item_id VARCHAR2(64),
      pluggy_account_id VARCHAR2(64),
      external_transaction_id VARCHAR2(128) NOT NULL,
      record_type VARCHAR2(24) DEFAULT 'TRANSACTION' NOT NULL,
      transaction_date TIMESTAMP WITH TIME ZONE,
      description VARCHAR2(512),
      amount NUMBER(18,2),
      currency_code VARCHAR2(8),
      account_name VARCHAR2(256),
      account_type VARCHAR2(64),
      balance_amount NUMBER(18,2),
      raw_json CLOB CHECK (raw_json IS JSON),
      source_system VARCHAR2(32) DEFAULT 'PLUGGY' NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;`;
  const uq = `
BEGIN
  EXECUTE IMMEDIATE q'[CREATE UNIQUE INDEX uq_transacoes_pluggy_ext ON transacoes_pluggy (tenant_user_id, external_transaction_id)]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;`;
  const ix = `
BEGIN
  EXECUTE IMMEDIATE q'[CREATE INDEX ix_transacoes_pluggy_dt ON transacoes_pluggy (tenant_user_id, transaction_date)]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;`;
  await conn.execute(sql);
  await conn.execute(uq);
  await conn.execute(ix);
}

function toTimestamp(value) {
  const ms = Date.parse(String(value || ''));
  if (!Number.isFinite(ms)) return null;
  return new Date(ms);
}

function toNumber(value) {
  const n = Number(value);
  return Number.isFinite(n) ? n : null;
}

function isCreditCardTransaction(tx) {
  const category = String(tx?.category || tx?.categoryName || '').toUpperCase();
  const type = String(tx?.type || tx?.nature || '').toUpperCase();
  const accountType = String(tx?.accountType || tx?.account?.type || '').toUpperCase();
  const description = String(tx?.description || '').toUpperCase();
  return category.includes('CART')
    || accountType.includes('CREDIT')
    || type.includes('CREDIT_CARD')
    || description.includes('CARTAO');
}

function normalizeExternalTransactionId(tx) {
  const direct = String(tx?.id || tx?.transactionId || tx?.providerId || '').trim();
  if (direct) return direct;
  const accountId = String(tx?.accountId || tx?.account?.id || '').trim();
  const date = String(tx?.date || tx?.paymentDate || tx?.createdAt || '').trim();
  const amount = String(tx?.amount || '').trim();
  const description = String(tx?.description || '').trim();
  return `${accountId}|${date}|${amount}|${description}`.slice(0, 128);
}

function normalizeTransactionsFromWebhook(payload) {
  const data = payload?.data;
  if (Array.isArray(data)) return data;
  if (Array.isArray(data?.transactions)) return data.transactions;
  if (Array.isArray(payload?.transactions)) return payload.transactions;
  if (data && typeof data === 'object') return [data];
  return [];
}

function resolveTenantUserId(payload) {
  const candidates = [
    payload?.clientUserId,
    payload?.data?.clientUserId,
    payload?.item?.clientUserId,
    payload?.data?.item?.clientUserId,
    payload?.userId,
    payload?.data?.userId,
    payload?.tenantUserId,
    payload?.data?.tenantUserId
  ];
  const hit = candidates.find(value => String(value || '').trim());
  return String(hit || DEFAULT_TENANT_USER_ID).trim();
}

async function upsertTransactions(transactions, tenantUserId) {
  if (!Array.isArray(transactions) || !transactions.length) return { inserted: 0, skipped: 0 };
  let inserted = 0;
  let skipped = 0;
  await withConnection(async conn => {
    await ensureTransactionsTable(conn);
    for (const tx of transactions) {
      const externalId = normalizeExternalTransactionId(tx);
      if (!externalId) {
        skipped += 1;
        continue;
      }
      const itemId = String(tx?.itemId || tx?.item?.id || tx?.account?.itemId || '').trim();
      const accountId = String(tx?.accountId || tx?.account?.id || '').trim();
      const accountName = String(tx?.account?.name || tx?.accountName || '').trim();
      const accountType = String(tx?.accountType || tx?.account?.type || '').trim();
      const recordType = isCreditCardTransaction(tx) ? 'CARTAO_CREDITO' : 'CONTA_CORRENTE';

      await conn.execute(
        `
MERGE INTO transacoes_pluggy t
USING (
  SELECT :tenant_user_id AS tenant_user_id, :external_transaction_id AS external_transaction_id FROM dual
) src
ON (t.tenant_user_id = src.tenant_user_id AND t.external_transaction_id = src.external_transaction_id)
WHEN MATCHED THEN UPDATE SET
  t.pluggy_item_id = :pluggy_item_id,
  t.pluggy_account_id = :pluggy_account_id,
  t.record_type = :record_type,
  t.transaction_date = :transaction_date,
  t.description = :description,
  t.amount = :amount,
  t.currency_code = :currency_code,
  t.account_name = :account_name,
  t.account_type = :account_type,
  t.raw_json = :raw_json,
  t.updated_at = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  tenant_user_id, pluggy_item_id, pluggy_account_id, external_transaction_id,
  record_type, transaction_date, description, amount, currency_code,
  account_name, account_type, raw_json, source_system, created_at, updated_at
) VALUES (
  :tenant_user_id, :pluggy_item_id, :pluggy_account_id, :external_transaction_id,
  :record_type, :transaction_date, :description, :amount, :currency_code,
  :account_name, :account_type, :raw_json, 'PLUGGY', SYSTIMESTAMP, SYSTIMESTAMP
)`,
        {
          tenant_user_id: String(tenantUserId || DEFAULT_TENANT_USER_ID),
          pluggy_item_id: itemId || null,
          pluggy_account_id: accountId || null,
          external_transaction_id: externalId.slice(0, 128),
          record_type: recordType,
          transaction_date: toTimestamp(tx?.date || tx?.paymentDate || tx?.createdAt),
          description: String(tx?.description || 'Transacao Pluggy').slice(0, 512),
          amount: toNumber(tx?.amount),
          currency_code: String(tx?.currencyCode || tx?.currency || 'BRL').slice(0, 8),
          account_name: accountName.slice(0, 256),
          account_type: accountType.slice(0, 64),
          raw_json: JSON.stringify(tx || {})
        }
      );
      inserted += 1;
    }
    await conn.commit();
  });
  return { inserted, skipped };
}

function getEventType(payload) {
  return String(
    payload?.event ||
    payload?.eventType ||
    payload?.type ||
    payload?.name ||
    ''
  ).trim().toLowerCase();
}

function getItem(payload) {
  return payload?.item || payload?.data?.item || payload?.data || payload;
}

function registerPluggyWebhookRoutes(app, deps = {}) {
  const noStore = typeof deps.noStore === 'function' ? deps.noStore : ((_, __, next) => next());
  const webhookSecret = String((deps.webhookSecret ?? WEBHOOK_SECRET) || '').trim();
  const upsertConnectionFn = typeof deps.upsertConnection === 'function' ? deps.upsertConnection : upsertConnection;
  const upsertTransactionsFn = typeof deps.upsertTransactions === 'function' ? deps.upsertTransactions : upsertTransactions;
  const resolveTenantUserIdFn = typeof deps.resolveTenantUserId === 'function' ? deps.resolveTenantUserId : resolveTenantUserId;

  app.post('/api/pluggy/webhook', noStore, async (req, res) => {
    try {
      if (webhookSecret) {
        const provided = String(req.headers['x-pluggy-webhook-secret'] || '').trim();
        if (!provided || provided !== webhookSecret) {
          return res.status(401).json({ message: 'Webhook Pluggy nao autorizado.' });
        }
      }

      const payload = req.body || {};
      const tenantUserId = String(resolveTenantUserIdFn(payload) || DEFAULT_TENANT_USER_ID).trim();
      const eventType = getEventType(payload);
      const item = getItem(payload);
      console.log(`[pluggy-webhook] recebido eventType=${eventType || 'unknown'} tenant=${tenantUserId}`);

      const isItemCreated = eventType === 'item/created' || eventType === 'item.created';
      const isTransactionsCreated = eventType === 'transactions/created' || eventType === 'transactions.created';

      if (isItemCreated) {
        const itemId = String(item?.id || '').trim();
        if (!itemId) {
          console.warn('[pluggy-webhook] item/created sem item.id');
          return res.status(400).json({ message: 'Webhook Pluggy sem item.id.' });
        }
        await upsertConnectionFn(item, tenantUserId);
        console.log(`[pluggy-webhook] item/created salvo itemId=${itemId}`);
        return res.status(200).json({ ok: true, eventType, itemId });
      }

      if (isTransactionsCreated) {
        const transactions = normalizeTransactionsFromWebhook(payload);
        const result = await upsertTransactionsFn(transactions, tenantUserId);
        console.log(`[pluggy-webhook] transactions/created processado count=${transactions.length} inserted=${result.inserted} skipped=${result.skipped}`);
        return res.status(200).json({ ok: true, eventType, ...result });
      }

      console.log(`[pluggy-webhook] evento ignorado eventType=${eventType || 'unknown'}`);
      return res.status(200).json({ ok: true, ignored: true, eventType: eventType || null });
    } catch (error) {
      console.error('[pluggy-webhook] erro:', error?.message || error);
      return res.status(500).json({ message: 'Falha ao processar webhook Pluggy.' });
    }
  });
}

module.exports = {
  registerPluggyWebhookRoutes,
  resolveTenantUserId,
  normalizeTransactionsFromWebhook,
  getEventType,
  getItem
};
