'use strict';

const { withConnection } = require('../../../workers/lib/oracle-db');

const TENANT_USER_ID = String(process.env.PLUGGY_TENANT_USER_ID || 'guilherme').trim();
const WEBHOOK_SECRET = String(process.env.PLUGGY_WEBHOOK_SECRET || '').trim();

async function ensureConnectionsTable(conn) {
  const sql = `
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE conexoes_bancarias (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_user_id VARCHAR2(128) NOT NULL,
      pluggy_item_id VARCHAR2(128) NOT NULL,
      provider_name VARCHAR2(256),
      status VARCHAR2(64),
      raw_json CLOB CHECK (raw_json IS JSON),
      source_system VARCHAR2(32) DEFAULT 'PLUGGY' NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;`;
  const uq = `
BEGIN
  EXECUTE IMMEDIATE q'[CREATE UNIQUE INDEX uq_conexoes_bancarias_item ON conexoes_bancarias (tenant_user_id, pluggy_item_id)]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;`;
  await conn.execute(sql);
  await conn.execute(uq);
}

async function upsertConnection(item) {
  await withConnection(async conn => {
    await ensureConnectionsTable(conn);
    await conn.execute(
      `
MERGE INTO conexoes_bancarias c
USING (SELECT :tenant_user_id AS tenant_user_id, :pluggy_item_id AS pluggy_item_id FROM dual) src
ON (c.tenant_user_id = src.tenant_user_id AND c.pluggy_item_id = src.pluggy_item_id)
WHEN MATCHED THEN UPDATE SET
  c.provider_name = :provider_name,
  c.status = :status,
  c.raw_json = :raw_json,
  c.updated_at = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  tenant_user_id,
  pluggy_item_id,
  provider_name,
  status,
  raw_json,
  source_system,
  created_at,
  updated_at
) VALUES (
  :tenant_user_id,
  :pluggy_item_id,
  :provider_name,
  :status,
  :raw_json,
  'PLUGGY',
  SYSTIMESTAMP,
  SYSTIMESTAMP
)`,
      {
        tenant_user_id: TENANT_USER_ID,
        pluggy_item_id: String(item?.id || '').trim(),
        provider_name: String(item?.connector?.name || item?.institution?.name || '').slice(0, 256),
        status: String(item?.status || '').slice(0, 64),
        raw_json: JSON.stringify(item || {})
      }
    );
    await conn.commit();
  });
}

function getEventType(payload) {
  return String(
    payload?.event ||
    payload?.eventType ||
    payload?.type ||
    payload?.name ||
    ''
  ).trim().toLowerCase();
}

function getItem(payload) {
  return payload?.item || payload?.data?.item || payload?.data || payload;
}

function registerPluggyWebhookRoutes(app, deps = {}) {
  const noStore = typeof deps.noStore === 'function' ? deps.noStore : ((_, __, next) => next());

  app.post('/api/pluggy/webhook', noStore, async (req, res) => {
    try {
      if (WEBHOOK_SECRET) {
        const provided = String(req.headers['x-pluggy-webhook-secret'] || '').trim();
        if (!provided || provided !== WEBHOOK_SECRET) {
          return res.status(401).json({ message: 'Webhook Pluggy não autorizado.' });
        }
      }

      const payload = req.body || {};
      const eventType = getEventType(payload);
      const item = getItem(payload);

      const isItemCreated = eventType === 'item/created' || eventType === 'item.created';
      if (!isItemCreated) {
        return res.status(202).json({ ok: true, ignored: true, eventType: eventType || null });
      }

      const itemId = String(item?.id || '').trim();
      if (!itemId) {
        return res.status(400).json({ message: 'Webhook Pluggy sem item.id.' });
      }

      await upsertConnection(item);
      return res.status(200).json({ ok: true, eventType, itemId });
    } catch (error) {
      console.error('[pluggy-webhook] erro:', error?.message || error);
      return res.status(500).json({ message: 'Falha ao processar webhook Pluggy.' });
    }
  });
}

module.exports = {
  registerPluggyWebhookRoutes
};

