name: Deploy para Oracle Cloud

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Enviar arquivos via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ubuntu
          key: ${{ secrets.OCI_KEY }}
          source: "."
          target: "/home/ubuntu/controle-financeiro"

      - name: Reiniciar o Servidor
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ubuntu
          key: ${{ secrets.OCI_KEY }}
          script: |
            cd /home/ubuntu/controle-financeiro
            npm install
            pm2 restart all || node server.js &
# teste final
